FROM centos:centos6
MAINTAINER Fabien MARTY <fabien.marty@gmail.com>

ENV DCO_CRONIE_START=1 \
    DCO_RSYSLOG_START=1 \
    DCO_RSYSLOG_REMOTE_HOST=null \
    DCO_RSYSLOG_REMOTE_PORT=514

# Update the image
RUN yum update -y

# Add runtime dependencies
ADD root/build/add_runtime_dependencies.sh /build/add_runtime_dependencies.sh
RUN /build/add_runtime_dependencies.sh

# Add build dependencies
ADD root/build/add_buildtime_dependencies.sh /build/add_buildtime_dependencies.sh
RUN /build/add_buildtime_dependencies.sh

 # Build logger
ADD root/build/logger.sh /build/logger.sh
RUN /build/logger.sh

# Add "S6 overlay" (https://github.com/just-containers/s6-overlay)
ADD root/build/s6_overlay.sh /build/s6_overlay.sh
RUN /build/s6_overlay.sh

# Build and install rsyslog
ADD root/build/rsyslog.sh /build/rsyslog.sh
RUN /build/rsyslog.sh

# Build and install cronie
ADD root/build/cronie.sh /build/cronie.sh
RUN /build/cronie.sh

# Add fake RPM
ADD root/build/add_fake_rpm.sh /build/add_fake_rpm.sh
ADD root/build/centos_opinionated.spec /build/centos_opinionated.spec
RUN /build/add_fake_rpm.sh

# Remove build dependencies
ADD root/build/remove_buildtime_dependencies.sh /build/remove_buildtime_dependencies.sh
RUN /build/remove_buildtime_dependencies.sh

# Add custom (other) files
COPY root /

ENTRYPOINT ["/init"]
